// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5-yKYq7jWraDcnRTvibQhgsKTliSH9g',
    appId: '1:764703627411:web:aebfa0f43f74dac0b99566',
    messagingSenderId: '764703627411',
    projectId: 'book-store-fajri-225',
    authDomain: 'book-store-fajri-225.firebaseapp.com',
    storageBucket: 'book-store-fajri-225.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIcdsMUJhjZ213etU8PpptZn1mNGlysM',
    appId: '1:764703627411:android:22bd7edab44ed805b99566',
    messagingSenderId: '764703627411',
    projectId: 'book-store-fajri-225',
    storageBucket: 'book-store-fajri-225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1OSLuynL0Scjq_M7-hQjBu78EOlzD8xc',
    appId: '1:764703627411:ios:df6db31771477b5ab99566',
    messagingSenderId: '764703627411',
    projectId: 'book-store-fajri-225',
    storageBucket: 'book-store-fajri-225.firebasestorage.app',
    iosBundleId: 'com.example.projectTokoBuku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1OSLuynL0Scjq_M7-hQjBu78EOlzD8xc',
    appId: '1:764703627411:ios:df6db31771477b5ab99566',
    messagingSenderId: '764703627411',
    projectId: 'book-store-fajri-225',
    storageBucket: 'book-store-fajri-225.firebasestorage.app',
    iosBundleId: 'com.example.projectTokoBuku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM5-yKYq7jWraDcnRTvibQhgsKTliSH9g',
    appId: '1:764703627411:web:2cd817856e269c49b99566',
    messagingSenderId: '764703627411',
    projectId: 'book-store-fajri-225',
    authDomain: 'book-store-fajri-225.firebaseapp.com',
    storageBucket: 'book-store-fajri-225.firebasestorage.app',
  );

}